diff --git a/src/finint_lab/report.py b/src/finint_lab/report.py
new file mode 100644
index 0000000000000000000000000000000000000000..040e27cd1474f62a0359463f900565a1f795594a
--- /dev/null
+++ b/src/finint_lab/report.py
@@ -0,0 +1,71 @@
+from __future__ import annotations
+
+from pathlib import Path
+
+from finint_lab.analyze import AnalysisResults, summarize_alerts
+
+
+REPORT_TEMPLATE = """
+# FININT Suspicious Transactions Analysis Report
+
+**Dataset:** {dataset_name}
+
+## Executive Summary
+{summary_paragraph}
+
+## Alert Summary
+{alert_table}
+
+## Key Alerts (Top 10 by Risk Score)
+{top_alerts}
+
+## Graph Analysis
+The transaction graph is saved to `{graph_path}`. Review it for hubs, clusters, and
+cycles that could indicate layering or round-tripping behavior.
+
+## Recommended Actions
+- Validate the beneficial ownership of highlighted counterparties.
+- Request supporting documentation for transactions linked to high-risk jurisdictions.
+- Escalate high-risk alerts for enhanced due diligence and potential SAR/STR filing.
+
+---
+Report generated by the FININT Suspicious Transactions Analysis Lab.
+""".strip()
+
+
+def _format_alert_table(summary: dict[str, int]) -> str:
+    header = "| Alert Type | Count |\n| --- | ---: |"
+    rows = [f"| {alert_type} | {count} |" for alert_type, count in summary.items()]
+    return "\n".join([header, *rows])
+
+
+def _format_top_alerts(alerts) -> str:
+    lines = []
+    for alert in sorted(alerts, key=lambda a: a.risk_score, reverse=True)[:10]:
+        lines.append(
+            f"- **{alert.alert_type} ({alert.risk_score})**: {alert.description} "
+            f"(Transactions: {', '.join(alert.related_transactions)})"
+        )
+    return "\n".join(lines) if lines else "No alerts generated."
+
+
+def write_report(
+    dataset_name: str,
+    results: AnalysisResults,
+    output_path: Path,
+) -> Path:
+    summary = summarize_alerts(results.alerts)
+    summary_paragraph = (
+        f"Generated {len(results.alerts)} alerts across {len(summary)} categories. "
+        "High-risk jurisdiction flows and structuring indicators were prioritized for review."
+    )
+    report_body = REPORT_TEMPLATE.format(
+        dataset_name=dataset_name,
+        summary_paragraph=summary_paragraph,
+        alert_table=_format_alert_table(summary),
+        top_alerts=_format_top_alerts(results.alerts),
+        graph_path=results.graph_path.as_posix(),
+    )
+    output_path.parent.mkdir(parents=True, exist_ok=True)
+    output_path.write_text(report_body, encoding="utf-8")
+    return output_path
